site_name: Implantació de Sistemes Operatius - POL CASANOVA PUIG

nav:
- Introducció: index.md
- Sprint1:
    - Introducció al Sprint 1: Sprint1.md
    - Instal·lació del sistema operatiu: install.md
    - Particions: partitions.md
    - Llicenciament: llicence.md
    - Punts de restauració: rest.md
    - Configuració bàsica de xarxa: net.md
    - Instal·lació bàsica de programes: softinst.md
    - Gestors d'arrencada: gest.md
    - Recuperació de gestors d'arrencada: reboot.md
    - Clonezilla: cz.md
- Sprint2:
    - Introducció al Sprint 2: spr2.md
    - Fitxers importants: imp_files.md
    - Gestió d'usuaris: user_gest.md
    - Gestió de processos: proc_gest.md
    - Permisos especials i ACLs: special_perm.md
    - Aplicació de permisos especials i ACLs: sp_use.md
    - Sistema de fitxers: file_sys.md
    - Gestió de particions i compartició de recursos: share_src.md
    - Automatitzacions de Tasques: autotask.md
    - Còpies de Seguretat: sec_copy.md
    - Quotes per a usuaris i grups: quotes.md
- Sprint3:
    - Instal·lació domini LDAP: ldap.md
    - Configuració del client LDAP: client_ldap.md
    - Gestió del domini LDAP: gestio_ldap.md
    - Perfils mòbils i Compartició de recursos: smb_nfs.md

theme:
    name: material

