<<<<<<< HEAD
site_name: Implantació de Sistemes Operatius - POL CASANOVA PUIG
nav:
- Introducció: index.md
- Sprint1: Sprint1.md
theme: material
   

=======
site_name: My Docs
theme: 
name: material
>>>>>>> b18df821 (text)
